from functools import lru_cache
from typing import Literal

from pydantic import field_validator
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    app_name: str = "Chmaba API"
    environment: Literal["development", "test", "production"] = "development"
    database_url: str = "postgresql+asyncpg://postgres:postgres@127.0.0.1:5432/chmaba_v1"
    sync_database_url: str = "postgresql+psycopg://postgres:postgres@127.0.0.1:5432/chmaba_v1"
    jwt_secret: str = "chmaba-local-development-secret-change-me"
    # Access tokens are deliberately short-lived. A long sign-in (up to
    # jwt_remember_ttl_minutes) is carried by the rotating refresh token in the
    # httpOnly session cookie instead of by a long-lived bearer token.
    jwt_access_ttl_minutes: int = 15
    jwt_remember_ttl_minutes: int = 60 * 24 * 30
    # Lifetime of a normal (non "remember me") sign-in. Platform admins set the
    # effective default and maximum in the admin panel (PlatformSetting
    # overrides); a company owner may override the default per company, always
    # bounded by the platform maximum. These are env fallbacks.
    jwt_session_ttl_minutes: int = 60 * 8
    jwt_max_session_ttl_minutes: int = 60 * 24 * 30
    # Name of the httpOnly cookie holding the refresh token.
    session_cookie_name: str = "chmaba_refresh"
    google_client_id: str | None = None
    google_client_secret: str | None = None
    google_redirect_uri: str = "http://127.0.0.1:8000/api/v1/auth/google/callback"
    frontend_url: str = "http://localhost:5173"
    cors_origins: str = "http://localhost:5173"
    smtp_host: str = "127.0.0.1"
    smtp_port: int = 1025
    smtp_from: str = "no-reply@chmaba.local"
    smtp_username: str | None = None
    smtp_password: str | None = None
    smtp_use_tls: bool = False
    # Implicit TLS (port 465). STARTTLS uses ``smtp_use_tls`` instead.
    smtp_use_ssl: bool = False
    # Outbound provider. The effective values are usually set from the admin
    # panel (PlatformSetting overrides); these are env fallbacks.
    resend_api_key: str | None = None
    resend_webhook_secret: str | None = None
    mail_from_name: str | None = None
    mail_reply_to: str | None = None
    # The mailing send queue is drained by an in-process worker so a scheduler
    # is not required. Set false to rely on the cron script instead.
    mailing_queue_worker_enabled: bool = True
    mailing_queue_interval_seconds: int = 30
    # The onboarding drip (which stalled signups get which step) is generated by
    # an in-process worker too, so automatic onboarding mail does not depend on
    # an external cron that may not exist. Generation is idempotent and respects
    # the configured local send window, so a short interval is safe.
    mailing_drip_worker_enabled: bool = True
    mailing_drip_interval_seconds: int = 900
    mailhog_ui_url: str = "http://localhost:8025"
    # Absolute origin the API is reachable at, used to build one-click
    # unsubscribe links that recipients click from their mail client.
    api_public_url: str = "http://127.0.0.1:8000"
    # AI drafting for the admin Mailing tool. Provider-agnostic; the effective
    # values are usually set from the admin panel (PlatformSetting overrides)
    # and these env fields are only fallback defaults.
    ai_provider: str | None = None
    ai_api_key: str | None = None
    ai_model: str | None = None
    ai_base_url: str | None = None
    # Support assistant (/support/chat). A per-user sliding-window cap protects
    # the paid provider; the rest are hard cost/shape limits on each request.
    support_rate_limit_per_hour: int = 60
    support_max_question_chars: int = 1000
    support_max_history_turns: int = 8
    support_max_output_tokens: int = 800
    # ChmabaPay (https://pay.chmaba.com). "mock" is a local fake (no sandbox
    # exists); "live" calls the real API.
    chamabapay_mode: Literal["mock", "live"] = "mock"
    chamabapay_api_url: str = "https://pay.chmaba.com"
    chamabapay_api_key: str | None = None
    chamabapay_webhook_secret: str | None = None
    # Chmaba's own internal ChmabaPay store, used to collect plan fees.
    chamabapay_platform_store_id: str | None = None
    # Paid plans stay fully usable for this many hours past ``ends_at`` before
    # the Free fallback runs, so a missed renewal does not instantly pause a
    # merchant's stores. A payment inside the window reactivates with no gap.
    billing_grace_hours: int = 48
    # Telegram platform notifications (the internal "chmabagroup" operations
    # chat). Both must be set to enable; when blank every send is a safe no-op.
    telegram_bot_token: str | None = None
    telegram_chat_id: str | None = None
    # Local day boundary used by the daily Telegram digest job.
    telegram_digest_timezone: str = "Asia/Phnom_Penh"
    # Product images are stored on disk and served under media_url_prefix.
    media_root: str = "chmabapos_api/media"
    media_url_prefix: str = "/media"

    model_config = SettingsConfigDict(env_file="chmabapos_api/.env", env_file_encoding="utf-8", extra="ignore")

    @property
    def telegram_enabled(self) -> bool:
        return bool(self.telegram_bot_token and self.telegram_chat_id)

@lru_cache
def get_settings() -> Settings:
    return Settings()


settings = get_settings()
