"""add_customers

Revision ID: 0015c68cb701
Revises: 291c0199ffdc
Create Date: 2026-09-05 16:37:26.532616
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0015c68cb701'
down_revision: Union[str, None] = '291c0199ffdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customer_company_created', 'customers', ['company_id', 'created_at'], unique=False)
    op.create_index('ix_customer_company_phone', 'customers', ['company_id', 'phone'], unique=False)
    op.create_index(op.f('ix_customers_company_id'), 'customers', ['company_id'], unique=False)
    op.add_column('orders', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'customers', ['customer_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.drop_column('orders', 'customer_id')
    op.drop_index(op.f('ix_customers_company_id'), table_name='customers')
    op.drop_index('ix_customer_company_phone', table_name='customers')
    op.drop_index('ix_customer_company_created', table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
