"""add_store_tax_rate

Revision ID: 359864e3b84e
Revises: 0015c68cb701
Create Date: 2026-09-05 17:45:21.246812
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '359864e3b84e'
down_revision: Union[str, None] = '0015c68cb701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stores', sa.Column('service_tax_rate', sa.Numeric(precision=5, scale=2), nullable=False, server_default=sa.text('10.00')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'service_tax_rate')
    # ### end Alembic commands ###
