"""add_company_contact_fields

Revision ID: 6aae2c557708
Revises: b0efc6f1a3a1
Create Date: 2026-09-06 00:06:10.717063
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6aae2c557708'
down_revision: Union[str, None] = 'b0efc6f1a3a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('email', sa.String(length=320), nullable=True))
    op.add_column('companies', sa.Column('phone', sa.String(length=40), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'phone')
    op.drop_column('companies', 'email')
    # ### end Alembic commands ###
