"""add_product_image

Revision ID: 8ea7a4929ca6
Revises: bd0a63ec16b6
Create Date: 2026-09-06 18:33:06.770809
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8ea7a4929ca6'
down_revision: Union[str, None] = 'bd0a63ec16b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
