"""add_shifts

Revision ID: ac3ce429f6cb
Revises: 359864e3b84e
Create Date: 2026-09-05 17:56:13.779617
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ac3ce429f6cb'
down_revision: Union[str, None] = '359864e3b84e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('opening_float', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sales_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cash_refunds', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('expected_cash', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('counted_cash', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shift_store_opened', 'shifts', ['store_id', 'opened_at'], unique=False)
    op.create_index('ix_shift_user_status', 'shifts', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_shifts_store_id'), 'shifts', ['store_id'], unique=False)
    op.create_index(op.f('ix_shifts_user_id'), 'shifts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shifts_user_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_store_id'), table_name='shifts')
    op.drop_index('ix_shift_user_status', table_name='shifts')
    op.drop_index('ix_shift_store_opened', table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
