"""add platform admin and audit logs

Revision ID: aeb47c36505e
Revises: ef4762f8a9f4
Create Date: 2026-09-04 21:21:53.501740
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aeb47c36505e'
down_revision: Union[str, None] = 'ef4762f8a9f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.add_column('companies', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.alter_column('companies', 'is_active', server_default=None)
    op.create_index(op.f('ix_companies_is_active'), 'companies', ['is_active'], unique=False)
    op.add_column('users', sa.Column('platform_role', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_users_platform_role'), 'users', ['platform_role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_platform_role'), table_name='users')
    op.drop_column('users', 'platform_role')
    op.drop_index(op.f('ix_companies_is_active'), table_name='companies')
    op.drop_column('companies', 'is_active')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index('ix_audit_log_created', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
