"""add_store_preferences_notifications

Revision ID: b0efc6f1a3a1
Revises: ac3ce429f6cb
Create Date: 2026-09-05 22:38:59.359474
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b0efc6f1a3a1'
down_revision: Union[str, None] = 'ac3ce429f6cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.String(length=600), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_store_created', 'notifications', ['store_id', 'created_at'], unique=False)
    op.create_index('ix_notification_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_store_id'), 'notifications', ['store_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.add_column('stores', sa.Column('preferences', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stores', 'preferences')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_store_id'), table_name='notifications')
    op.drop_index('ix_notification_user_created', table_name='notifications')
    op.drop_index('ix_notification_store_created', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
