"""add_tip_points_taxid

Revision ID: bd0a63ec16b6
Revises: 616de8046962
Create Date: 2026-09-06 13:38:11.562462
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd0a63ec16b6'
down_revision: Union[str, None] = '616de8046962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('tax_id', sa.String(length=80), nullable=True))
    op.add_column('customers', sa.Column('points', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0.00')))
    op.add_column('orders', sa.Column('tip', sa.Numeric(precision=12, scale=2), nullable=False, server_default=sa.text('0.00')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'tip')
    op.drop_column('customers', 'points')
    op.drop_column('companies', 'tax_id')
    # ### end Alembic commands ###
