"""add_product_image_col

Revision ID: bfbd778dbbfd
Revises: 8ea7a4929ca6
Create Date: 2026-09-06 19:29:10.404140
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bfbd778dbbfd'
down_revision: Union[str, None] = '8ea7a4929ca6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image')
    # ### end Alembic commands ###
