"""add exchange rates and order tenders

Revision ID: ef4762f8a9f4
Revises: e50481e1690f
Create Date: 2026-09-04 16:18:15.879157
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ef4762f8a9f4'
down_revision: Union[str, None] = 'e50481e1690f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('base_currency_code', sa.String(length=3), nullable=False),
    sa.Column('quote_currency_code', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['base_currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['quote_currency_code'], ['currencies.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'base_currency_code', 'quote_currency_code', 'effective_from', name='uq_exchange_rate_effective')
    )
    op.create_index('ix_exchange_rate_lookup', 'exchange_rates', ['company_id', 'base_currency_code', 'quote_currency_code', 'effective_from'], unique=False)
    op.create_index(op.f('ix_exchange_rates_company_id'), 'exchange_rates', ['company_id'], unique=False)
    op.create_table('order_tenders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('base_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_tender_order', 'order_tenders', ['order_id', 'kind'], unique=False)
    op.create_index(op.f('ix_order_tenders_order_id'), 'order_tenders', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_tenders_order_id'), table_name='order_tenders')
    op.drop_index('ix_order_tender_order', table_name='order_tenders')
    op.drop_table('order_tenders')
    op.drop_index(op.f('ix_exchange_rates_company_id'), table_name='exchange_rates')
    op.drop_index('ix_exchange_rate_lookup', table_name='exchange_rates')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
