"""add_held_orders

Revision ID: fbcb961cfab4
Revises: 9676d101a91b
Create Date: 2026-09-05 14:20:43.627179
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fbcb961cfab4'
down_revision: Union[str, None] = '9676d101a91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('held_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('items', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_held_order_store_created', 'held_orders', ['store_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_held_orders_store_id'), 'held_orders', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_held_orders_store_id'), table_name='held_orders')
    op.drop_index('ix_held_order_store_created', table_name='held_orders')
    op.drop_table('held_orders')
    # ### end Alembic commands ###
